### ISSUE TITLE
Build on Adroit

### ISSUE THREAD

**Issue by henryiii** [ammarhakim/gkyl#22]
I followed the directions, but ran into an error:

Before I try to debug it, are there any quick fixes already known?

```bash
git clone git@github.com:ammarhakim/gkyl.git
cd gkyl/
./machines/mkdeps.adroit.sh
./machines/configure.adroit.sh
./waf build install
```

```
Waf: Entering directory `/home/henryfs/gkyl/build'
[  1/782] Compiling Lib/lfs.c
[  2/782] Compiling Lib/base64.cpp
[  3/782] Compiling Lib/whereami.c
[  4/782] Compiling Lib/gkyl_ipow.cpp
Waf: Leaving directory `/home/henryfs/gkyl/build'
Build failed
Traceback (most recent call last):
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 180, in process
    ret=self.run()
  File "<string>", line 27, in f
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 173, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Context.py", line 181, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 598, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 545, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: ['icpc', '-O3', '-std=c++17', '-fPIC', '-ILib', '-I../Lib', '-ICuda', '-I../Cuda', '-I../../gkylsoft/luajit/include/luajit-2.1', '../Lib/gkyl_ipow.cpp', '-c', '-o/home/henryfs/gkyl/build/Lib/gkyl_ipow.cpp.1.o']
Traceback (most recent call last):
  File "<string>", line 30, in run
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


Traceback (most recent call last):
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 180, in process
    ret=self.run()
  File "<string>", line 27, in f
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 173, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Context.py", line 181, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 598, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 545, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: ['icpc', '-O3', '-std=c++17', '-fPIC', '-ILib', '-I../Lib', '-ICuda', '-I../Cuda', '-I../../gkylsoft/luajit/include/luajit-2.1', '../Lib/base64.cpp', '-c', '-o/home/henryfs/gkyl/build/Lib/base64.cpp.1.o']
Traceback (most recent call last):
  File "<string>", line 30, in run
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


Traceback (most recent call last):
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 180, in process
    ret=self.run()
  File "<string>", line 27, in f
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 173, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Context.py", line 181, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 598, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 545, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: ['icc', '-O3', '-Wall', '-fPIC', '-ILib', '-I../Lib', '-ICuda', '-I../Cuda', '-I../../gkylsoft/luajit/include/luajit-2.1', '../Lib/lfs.c', '-c', '-o/home/henryfs/gkyl/build/Lib/lfs.c.1.o']
Traceback (most recent call last):
  File "<string>", line 30, in run
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


Traceback (most recent call last):
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 180, in process
    ret=self.run()
  File "<string>", line 27, in f
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Task.py", line 173, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Context.py", line 181, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 598, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/home/henryfs/gkyl/.waf-2.0.19-1f3c580272b15a03d2566843c5fe872a/waflib/Utils.py", line 545, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: ['icc', '-O3', '-Wall', '-fPIC', '-ILib', '-I../Lib', '-ICuda', '-I../Cuda', '-I../../gkylsoft/luajit/include/luajit-2.1', '../Lib/whereami.c', '-c', '-o/home/henryfs/gkyl/build/Lib/whereami.c.1.o']
Traceback (most recent call last):
  File "<string>", line 30, in run
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Also, have you considered CMake instead of custom scripts for every machine? If you need help getting started, I can point you at a book about using Modern CMake (that I wrote).

**Comment by manauref** [comment]
Can you post your module list and .bashrc here please? It might be a conflict with your environment.

I just tried installing, configuring and building on Adroit a few hours ago and it worked for me (and I believe @nmandell has also been building today).

**Comment by ammarhakim** [comment]
Hi @henryiii .... we use a build tool. The script you are running is just to get the configure on a specific machine. It is not the build system per-se. We use Adriot all the time and things work on it smoothly. Unfortunately we are at present hacking at the code a lot and this may mean some instability in the builds. We will try and look at your problem (@manauref can help).

**Comment by henryiii** [comment]
Loading some modules beforehand fixed the problem, thanks Noah, it now compiles! Could we add a little printout of recommended modules to either mkdeps or configure, the later seems better, but might cause the configure to need to be rerun after the printout.

(Modern) CMake has the ability to download dependencies, and integrates with all IDEs, CUDA, etc. It just is a (long term) suggestion that would reduce custom scripts a bit.

**Comment by henryiii** [comment]
Could we add a little printout of recommended modules somewhere?

```
module load rh/devtoolset/8 intel intel-mpi cudatoolkit/10.1 anaconda3
```

I'd be happy to do it but need to know where.

**Comment by manauref** [comment]
They are typically found at the top of the configure file. This is the case
for Adroit (machines/config.adroit.sh).
